[package]
name = "blink"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "blink"
path = "src/main.rs"

[features]
default = ["pod"]
pod = []

[dependencies]
bbx_daisy = { path = "../../../../bbx_audio/bbx_daisy", default-features = false, features = ["pod"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(feature, values(\"pod\"))"] }

[profile.release]
opt-level = "s"
lto = true
panic = "abort"
codegen-units = 1
