[package]
name = "daisy"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "daisy"
path = "src/main.rs"

[dependencies]
bbx_daisy = { path = "../../../../bbx_audio/bbx_daisy", default-features = false, features = ["seed"] }

[profile.release]
opt-level = "s"
lto = true
panic = "abort"
codegen-units = 1
