[package]
name = "audio-test"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "audio-test"
path = "src/main.rs"

[dependencies]
bbx_daisy = { path = "../../../../bbx_audio/bbx_daisy", default-features = false, features = ["pod"] }
cortex-m = "0.7"
cortex-m-rt = "0.7"
stm32h7xx-hal = { version = "0.16", features = ["stm32h750v", "rt"] }
embedded-hal = "0.2"
libm = "0.2"

[profile.release]
opt-level = "s"
lto = true
panic = "abort"
codegen-units = 1
