TARGET = simple_oscillator
CPP_SOURCES = simple_oscillator.cpp

LIB_DAISY_DIR = ../../lib/lib-daisy/
DAISY_SP_DIR = ../../lib/daisy-sp/

SYSTEM_FILES_DIR = $(LIB_DAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
